server:
  port: 9003

spring:
  application:
    name: dispatcher-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 10000 # 10s
      request-read-timeout: 10000 # 10s
      fail-fast: false # In production set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
    function:
      definition: pack|label
    stream:
      bindings:
        packlabel-in-0:
          # the actual name at the broker that the binder binds to
          destination: order-accepted
          # the consumer group interested in the destination
          group: ${spring.application.name}
        packlabel-out-0:
          destination: order-dispatched

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  system: Polar Bookshop

management:
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, bindings, configprops, env, functions, heapdump, info, loggers, mappings, prometheus
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}